app/models.py
class Articles:
    '''
    articles class to define article objects
    '''
    def __init__(self, title, description, image, publishedAt, author, url):
        self.title = title
        self.description = description
        self.image = image
        self.publishedAt = publishedAt
        self.author = author
        self.url = url




class News:
    '''
    all news class to define news objects
    '''
    def __init__(self, name, author, url,description, country,category, id):
        self.name = name
        self.author = author
        self.url = url
        self.description = description
        self.country = country
        self.category = category
        self.id = id
    







        

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options

bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)


    #setting config
    from .request import configure_request
    configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint


main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template, request, redirect, url_for
from . import main
from ..request import get_articles, get_news


#views
@main.route('/')
def index():
    '''
    view root page that returns the index page and its data
    '''
    title = "Home || News Sources"

    all_news = get_news('sports')
    general_news = get_news('general')
    tech_news = get_news('technology')
    bus_news = get_news('business')
    sci_news = get_news('science')


    # print(all_news)


    return render_template('index.html', title= title, sports = all_news, general = general_news, technology = tech_news, business = bus_news, science = sci_news)

# Views
@main.route('/news/<int:id>')
def news(id):
    '''
    View movie page function that returns the movie details page and its data
    '''
    news = get_news(id)

    
    return render_template('index.html', news = news)



@main.route('/articles/<source_id>')
def articles(source_id):
    '''
    function that returns articles by source id
    '''

    article_source = get_articles(source_id)
    title = f'{source_id}| Articles'
    return render_template('articles.html',title = title, name = source_id, news = article_source )

app/templates/articles.html
{% extends 'base.html' %} {% block content %}


<div class="container-fluid">
    <div class="row">
        {% for article in news %}
        <div class="col-md-4">
            <div class="thumbnail">
                <div class="details">
                    <h4>{{article.description | truncate(100)}}</h4>
                    <a href="{{article.url}}" target="_blank"> Read Full article </a>
                    <p>Posted on : {{article.publishedAt}}</p>
                </div>
                <a>
                    <img src="{{article.image}}" class="img-responsive" styles="height:20px">
                </a>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html' %} {% block styles %} {{super()}}

<link href="{{url_for('static',filename='css/index.css')}}" rel="stylesheet">
<link href="{{url_for('static',filename='css/bootstrap-grid.css')}}" rel="stylesheet">
<link href="{{url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet"> {% endblock %} {% block navbar %} {% include 'nav.html' %} {% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% block content %}

<hr>
<div style="margin-top: 20px;" class="container-fluid">
    <div class="row">
        <h2 style="text-align: center;color:#00013A;">General news </h2>
        <hr> {% for all_news in general %}
        <div class="col-md-2">
            <div class="thumbnail">
                <div class="details">
                    <h4>{{all_news.name}}</a>
                    </h4>
                    <p>{{all_news.description | truncate(100)}}</p>
                    <p><a href="/articles/{{ all_news.id}}">Read {{all_news.name}} Articles</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<hr>
<div style="margin-top: 20px;" class="container-fluid">
    <div class="row">
        <h2 style="text-align: center;color:blue;">Business news </h2>
        <hr> {% for all_news in business %}
        <div class="col-md-2">
            <div class="thumbnail">
                <div class="details">
                    <h4>{{all_news.name}}</h4>
                    <p>{{all_news.description | truncate(100)}}</p>
                    <p><a href="/articles/{{ all_news.id}}">Read {{all_news.name}} Articles</a></p>

                </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
<hr>
<div style="margin-top: 20px;" class="container-fluid">
    <div class="row">
        <h2 style="text-align: center;color:blue;">Sports news </h2>
        <hr> {% for all_news in sports %}
        <div class="col-md-2">
            <div class="thumbnail">
                <div class="details">
                    <h4>{{all_news.name}}</a>
                    </h4>
                    <p>{{all_news.description | truncate(100)}}</p>
                    <p><a href="/articles/{{ all_news.id}}">Read {{all_news.name}} Articles</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<hr>
<div style="margin-top: 20px;" class="container-fluid">
    <div class="row">
        <h2 style="text-align: center;color:blue;">Tech news </h2>
        <hr> {% for all_news in technology %}
        <div class="col-md-2">
            <div class="thumbnail">
                <div class="details">
                    <h4>{{all_news.name}}</a>
                    </h4>
                    <p>{{all_news.description | truncate(100)}}</p>
                    <p><a href="/articles/{{ all_news.id}}">Read {{all_news.name}} Articles</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<hr>
<div style="margin-top: 20px;" class="container-fluid">
    <div class="row">

        <h2 style="text-align: center;color:blue;">Science news
        </h2>
        {% for all_news in science %}
        <div style="margin-left: 90px;" class="col-md-2">
            <div class="thumbnail">
                <div class="details">
                    <h4>{{all_news.name}}</a>
                    </h4>
                    <p>{{all_news.description | truncate(100)}}</p>
                    <p><a href="/articles/{{ all_news.id}}">Read {{all_news.name}} Articles</a></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<hr> {% endblock %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/"><i><h1>NEWS  HIGHLIGHT</h1></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">
      </span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="navbar-brand" href="/">
                    <h2>Home</h2>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.articles',source_id = 'abc-news',per_page='10')}}">
                    <h2>Articles</h2>
                </a>
            </li>
        </ul>
    </div>
</nav>